version: '3.2'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    network_mode: host
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - /home/kubernetes/phystats/dockers/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - node_exporter
    restart: always

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8081:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    restart: always

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    network_mode: host
    ports:
      - 9100:9100
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--collector.textfile.directory=/node_exporter/prom'
    volumes:
      - /proc:/host/proc
      - /sys:/host/sys
      - /:/rootfs
    restart: always
  phystats:
    image: byuegv/phystats:latest
    container_name: phystats
    environment:
      - CLUSTER_ID=cluster-1
      - MACHINE_ADDRESS="127.0.0.1"
    network_mode: host
    entrypoint: ["/usr/bin/python3", "main.py"]
    command:
      - '--host=localhost'
      - '--port=9090'
      - '--kafka_host=kafka-server'
      - '--kafka_port=9092'
      - '--kafka_topic=phystats'
      - '--collect_interval=15.0'
      - '--consume_interval=15.0'
      - '--k8s_interval=15.0'
      - '--limit=10000'
      - '--role=collector,k8s_info'
    volumes:
      - /root/.kube:/root/.kube
    depends_on:
      - prometheus
    restart: always